### ISSUE TITLE
jgrade jar not found in gradescope example because of outdated run.sh

### ISSUE THREAD

**Issue by krenargashi** [tkutcher/jgrade#20]
This happens because run.sh uses "jgrade-1.0.0-all.jar", the name of the file though is "jgrade-1.0-all.jar".

Either change the filename or the code inside run.sh (best update to "jgrade-1.1-all.jar")

Nice and helpful project!

**Comment by tkutcher** [comment]
Sorry I didn't realize I wasn't getting notifications for this project! Thanks for the report - I updated that. I'm gonna post this on the README but if you have any interest in helping maintain this in general let me know!
